### PR TITLE
fix(query): Respect --deps and --explicit.

### LINKED ISSUE #1283: yay -Qu does not handle -e or -d; unlike pacman
#### Affected Version
`yay v9.4.7.r13.g11db63f - libalpm v12.0.1`

#### Issue
yay -Qu does not handle -e or -d; unlike pacman.

#### Steps to reproduce
1. Wait until your system has pending updates for packages installed both explicitly and as dependencies.
2. `pacman -Que` # Will only list packages installed explicitly
3. `yay -Que` # Will list packages installed both explicitly and as dependencies

#### Output
```
$ yay -Qu
archlinux-keyring 20200422-1 -> 20200603-1
iana-etc 20200511-1 -> 20200601-1
libksba 1.3.5-2 -> 1.4.0-1
librsvg 2:2.48.6-1 -> 2:2.48.7-1
libunrar 1:5.9.2-1 -> 1:5.9.3-2
libyaml 0.2.4-1 -> 0.2.5-1
linux-lts 5.4.43-1 -> 5.4.44-1
linux-lts-headers 5.4.43-1 -> 5.4.44-1
python2-setuptools 2:44.1.0-1 -> 2:44.1.1-1
qemu-guest-agent 5.0.0-6 -> 5.0.0-7
qt5-base 5.15.0-1 -> 5.15.0-2
qt5ct 0.41-4 -> 0.41-5
quassel-client 0.13.1-2 -> 0.13.1-3
signond 8.60-2 -> 8.60-3
systemd 245.6-1 -> 245.6-2
systemd-libs 245.6-1 -> 245.6-2
systemd-sysvcompat 245.6-1 -> 245.6-2
unrar 1:5.9.2-1 -> 1:5.9.3-2
v4l-utils 1.18.1-1 -> 1.20.0-1
$ yay -Que
archlinux-keyring 20200422-1 -> 20200603-1
iana-etc 20200511-1 -> 20200601-1
libksba 1.3.5-2 -> 1.4.0-1
librsvg 2:2.48.6-1 -> 2:2.48.7-1
libunrar 1:5.9.2-1 -> 1:5.9.3-2
libyaml 0.2.4-1 -> 0.2.5-1
linux-lts 5.4.43-1 -> 5.4.44-1
linux-lts-headers 5.4.43-1 -> 5.4.44-1
python2-setuptools 2:44.1.0-1 -> 2:44.1.1-1
qemu-guest-agent 5.0.0-6 -> 5.0.0-7
qt5-base 5.15.0-1 -> 5.15.0-2
qt5ct 0.41-4 -> 0.41-5
quassel-client 0.13.1-2 -> 0.13.1-3
signond 8.60-2 -> 8.60-3
systemd 245.6-1 -> 245.6-2
systemd-libs 245.6-1 -> 245.6-2
systemd-sysvcompat 245.6-1 -> 245.6-2
unrar 1:5.9.2-1 -> 1:5.9.3-2
v4l-utils 1.18.1-1 -> 1.20.0-1
$ yay -Qud
archlinux-keyring 20200422-1 -> 20200603-1
iana-etc 20200511-1 -> 20200601-1
libksba 1.3.5-2 -> 1.4.0-1
librsvg 2:2.48.6-1 -> 2:2.48.7-1
libunrar 1:5.9.2-1 -> 1:5.9.3-2
libyaml 0.2.4-1 -> 0.2.5-1
linux-lts 5.4.43-1 -> 5.4.44-1
linux-lts-headers 5.4.43-1 -> 5.4.44-1
python2-setuptools 2:44.1.0-1 -> 2:44.1.1-1
qemu-guest-agent 5.0.0-6 -> 5.0.0-7
qt5-base 5.15.0-1 -> 5.15.0-2
qt5ct 0.41-4 -> 0.41-5
quassel-client 0.13.1-2 -> 0.13.1-3
signond 8.60-2 -> 8.60-3
systemd 245.6-1 -> 245.6-2
systemd-libs 245.6-1 -> 245.6-2
systemd-sysvcompat 245.6-1 -> 245.6-2
unrar 1:5.9.2-1 -> 1:5.9.3-2
v4l-utils 1.18.1-1 -> 1.20.0-1
```
```
$ pacman -Qu
archlinux-keyring 20200422-1 -> 20200603-1
iana-etc 20200511-1 -> 20200601-1
libksba 1.3.5-2 -> 1.4.0-1
librsvg 2:2.48.6-1 -> 2:2.48.7-1
libunrar 1:5.9.2-1 -> 1:5.9.3-2
libyaml 0.2.4-1 -> 0.2.5-1
linux-lts 5.4.43-1 -> 5.4.44-1
linux-lts-headers 5.4.43-1 -> 5.4.44-1
python2-setuptools 2:44.1.0-1 -> 2:44.1.1-1
qemu-guest-agent 5.0.0-6 -> 5.0.0-7
qt5-base 5.15.0-1 -> 5.15.0-2
qt5ct 0.41-4 -> 0.41-5
quassel-client 0.13.1-2 -> 0.13.1-3
signond 8.60-2 -> 8.60-3
systemd 245.6-1 -> 245.6-2
systemd-libs 245.6-1 -> 245.6-2
systemd-sysvcompat 245.6-1 -> 245.6-2
unrar 1:5.9.2-1 -> 1:5.9.3-2
v4l-utils 1.18.1-1 -> 1.20.0-1
$ pacman -Que
linux-lts 5.4.43-1 -> 5.4.44-1
linux-lts-headers 5.4.43-1 -> 5.4.44-1
qemu-guest-agent 5.0.0-6 -> 5.0.0-7
qt5ct 0.41-4 -> 0.41-5
quassel-client 0.13.1-2 -> 0.13.1-3
unrar 1:5.9.2-1 -> 1:5.9.3-2
$ pacman -Qud
archlinux-keyring 20200422-1 -> 20200603-1
iana-etc 20200511-1 -> 20200601-1
libksba 1.3.5-2 -> 1.4.0-1
librsvg 2:2.48.6-1 -> 2:2.48.7-1
libunrar 1:5.9.2-1 -> 1:5.9.3-2
libyaml 0.2.4-1 -> 0.2.5-1
python2-setuptools 2:44.1.0-1 -> 2:44.1.1-1
qt5-base 5.15.0-1 -> 5.15.0-2
signond 8.60-2 -> 8.60-3
systemd 245.6-1 -> 245.6-2
systemd-libs 245.6-1 -> 245.6-2
systemd-sysvcompat 245.6-1 -> 245.6-2
v4l-utils 1.18.1-1 -> 1.20.0-1
```
```
$ yay -Pg
{
        "aururl": "https://aur.archlinux.org",
        "buildDir": "/home/patricol/.cache/yay",
        "absdir": "/home/patricol/.cache/yay/abs",
        "editor": "",
        "editorflags": "",
        "makepkgbin": "makepkg",
        "makepkgconf": "",
        "pacmanbin": "pacman",
        "pacmanconf": "/etc/pacman.conf",
        "redownload": "no",
        "rebuild": "tree",
        "answerclean": "All",
        "answerdiff": "All",
        "answeredit": "None",
        "answerupgrade": "None",
        "gitbin": "git",
        "gpgbin": "gpg",
        "gpgflags": "",
        "mflags": "",
        "sortby": "popularity",
        "searchby": "name-desc",
        "gitflags": "",
        "removemake": "yes",
        "sudobin": "sudo",
        "sudoflags": "",
        "requestsplitn": 150,
        "sortmode": 1,
        "completionrefreshtime": 7,
        "sudoloop": true,
        "timeupdate": false,
        "devel": false,
        "cleanAfter": true,
        "provides": false,
        "pgpfetch": true,
        "upgrademenu": true,
        "cleanmenu": true,
        "diffmenu": true,
        "editmenu": false,
        "combinedupgrade": false,
        "useask": false,
        "batchinstall": false
}
```

### PR DESCRIPTION
**Pull request by ghost**
This fixes #1283.

```bash
yay --query --upgrades [--explicit|--deps]
```
will not return same packages pacman does extended with AUR packages.

```bash
yay --show --numberupgrades [--explicit|--deps]
```
will also work.

### CODE REVIEW

**Comment by Jguer** [comment]
Seems good, let me pull it, play around a bit with it (the filtering at the end may be a bit slow), and we'll go from there

File: cmd.go [hunk 1]
```diff
@@ -179,9 +180,32 @@ func handleCmd(cmdArgs *settings.Arguments, dbExecutor db.Executor) error {
 	return fmt.Errorf(gotext.Get("unhandled operation"))
 }
 
+func getFilter(cmdArgs *settings.Arguments) (upgrade.Filter, error) {
```
Comment (Jguer) [inline cmd.go:186]: Could you write a small docstring for this, explaing why it's necessary

**Comment by Jguer** [comment]
Thanks @xvqxy I'm merging
