### PR TITLE
fix: skip cache clean when no valid pacman cache directories exist  #2652

### LINKED ISSUE #2652: Clearing cache fails when no `pacman` cache directories exist
### Affected Version

```
yay v12.5.0 - libalpm v15.0.0
```

### Describe the bug

Following paths seem to be expected by `yay -Scc` and cause failure in clearing user home cache when non-existent

- `/var/cache/pacman/pkg/`
- `/var/lib/pacman/`

### Reproduction Steps

1. Use `tmpfs` for `pacman` cache
2. Attempt to clear `yay` cache after a fresh boot
3. Question my life choices

### Expected behavior

Expect `yay` to check if `pacman` cache directories exist prior to attempting to clear them

### Output

- When no `pacman` cache directories exist
   ```bash
   yay -Scc
   #> Cache directory: /var/cache/pacman/pkg/
   #> :: Do you want to remove all other packages from cache? [Y/n] y
   #> removing old packages from cache...
   #> error: could not access cache directory /var/cache/pacman/pkg/
   #> Database directory: /var/lib/pacman/
   #> :: Do you want to remove unused repositories? [Y/n] y
   #> removing unused sync repositories...
   #>  -> exit status 1
   ```
- When `pacman` cache directories **do** exist
   ```bash
   yay -Scc
   #> Cache directory: /var/cache/pacman/pkg/
   #> :: Do you want to remove ALL files from cache? [y/N] y
   #> removing all files from cache...
   #> 
   #> Database directory: /var/lib/pacman/
   #> :: Do you want to remove unused repositories? [Y/n] y
   #> removing unused sync repositories...
   #> 
   #> Build directory: /home/s0ands0/.cache/yay
   #> :: Do you want to remove ALL AUR packages from cache? [Y/n] y
   #> removing AUR packages from cache...
   ```

### Notes

Not really a big deal, I probably could've answered `n`o to the first two `pacman` related directories :shrug:

### PR DESCRIPTION
**Pull request by sarbojitrana**
# Fixes #2652 

## Problem

When all `CacheDir` paths are missing (e.g., when using tmpfs or after a fresh boot), `yay -Scc` attempts to invoke pacman, which results in:

```
    error: could not access cache directory
    -> exit status 1
```

In addition, execution continues into AUR cleaning logic, which can lead to runtime panics.

##  Solution

- Check whether at least one configured `CacheDir` exists
- If none exist:
  - Log an informative message
  - Return early, skipping both pacman and AUR clean steps

### Before the fix :

image

### After the fix:
image

Renamed ```/var/cache/pacman/pkg/``` to ```/var/cache/pacman/pkg_backup/``` to reproduce the issue.

### CODE REVIEW

File: clean.go [hunk 1]
```diff
@@ -64,10 +64,26 @@ func syncClean(ctx context.Context, run *runtime.Runtime, cmdArgs *parser.Argume
...
+		if validDirExists {
+			if err := run.CmdBuilder.Show(run.CmdBuilder.BuildPacmanCmd(ctx,
+				cmdArgs, run.Cfg.Mode, settings.NoConfirm)); err != nil {
+				return err
+			}
+		} else {
+			run.Logger.Println(gotext.Get("No valid pacman cache directories found. Skipping cache clean.")) 
+			return nil
 		}
+
```
Comment (Jguer) [inline clean.go]:
```suggestion
```

**Comment by sarbojitrana** [comment]
Hey @Jguer i've removed that extra line as suggested by you, please review the PR

**Comment by sarbojitrana** [comment]
hey @Jguer , just following up on the PR, I've addressed the requested change and verified locally. Would appreciate a quick review whenever you have the time. Thanks

**Review by Jguer — APPROVED** [review]
Let's get this merged in, thanks @sarbojitrana
