### PR TITLE
Ignore errors while diffing

### LINKED ISSUE #1091: yay 9.4 exits after showing upgrade diffs
#### Affected Version
yay v9.4.2.r0.g290d3d2 - libalpm v12.0.0

#### Issue
Since upgrading to yay v9.4 (I think), I can't upgrade AUR packages anymore - yay just quits after showing the diffs.

#### Steps to reproduce
1. Run `yay -Suy`
2. Answer prompts until diffs are shown (with just enter, but explicitly selecting something doesn't seem to make a difference)
3. Exit diffs with `q`

#### Output
```
$ yay -Suy 
:: Synchronizing package databases...
 core is up to date
 extra is up to date
 community is up to date
 multilib is up to date
 qt-debug                      36.8 KiB  1842 KiB/s 00:00 [##############################] 100%
:: Starting full system upgrade...
 there is nothing to do
:: Searching databases for updates...
:: Searching AUR for updates...
:: Checking development packages...
 -> Missing AUR Packages:  adwaita-qt5  cope-cmpl-git  libgcj17-bin  libhttpseverywhere-git  pcmciautils  pdftk-bin  python2-faulthandler  python2-plaster  rofimoji-git  skypeforlinux-bin  tor-browser-en  yaourt
 -> Orphaned AUR Packages:  firebird-nspire  logcat-color  python-plaster  python-plaster-pastedeploy
 -> Flagged Out Of Date AUR Packages:  firebird-nspire  keepassc  lemonbar-git  omnisharp-roslyn  uzbl-browser  uzbl-core
:: 9 Packages to upgrade.
9  aur/camlpdf                  2.2.p1-1                 -> 2.3-1
8  aur/cpdf                     2.2.1-1                  -> 2.3-1
7  aur/google-chrome-dev        79.0.3938.0-1            -> 79.0.3945.8-1
6  aur/package-query            1.9-3                    -> 1.10-1
5  aur/python38                 3.8.0b4-1                -> 3.8.0-1
4  aur/teamviewer-beta          14.5.5819-1              -> 14.7.1965-1
3  devel/deltachat-desktop-git  v0.201.0.r91.g0a052400-1 -> latest-commit
2  devel/edid-decode-git        r200.dc8afbf-1           -> latest-commit
1  devel/firebird-nspire        1.3-1                    -> latest-commit
==> Packages to exclude: (eg: "1 2 3", "1-3", "^4" or repo name)
==> 
:: Checking for conflicts...
:: Checking for inner conflicts...
[Repo Make: 2]  ocaml-compiler-libs-4.09.0-1  ocaml-findlib-1.8.1-4
[Aur: 9]  camlpdf-2.3-1  cpdf-2.3-1  google-chrome-dev-79.0.3945.8-1  package-query-1.10-1  firebird-nspire-1.3-1  python38-3.8.0-1  teamviewer-beta-14.7.1965-1  deltachat-desktop-git-v0.105.0.pre2.r235.g7424ae5-1  edid-decode-git-r182.ab18bef-1

==> Remove make dependencies after install? [y/N] 
  9 camlpdf                          (Installed) (Build Files Exist)
  8 cpdf                             (Installed) (Build Files Exist)
  7 google-chrome-dev                (Installed) (Build Files Exist)
  6 package-query                    (Installed) (Build Files Exist)
  5 firebird-nspire                  (Installed) (Build Files Exist)
  4 python38                         (Installed) (Build Files Exist)
  3 teamviewer-beta                  (Installed) (Build Files Exist)
  2 deltachat-desktop-git            (Installed) (Build Files Exist)
  1 edid-decode-git                  (Installed) (Build Files Exist)
==> Packages to cleanBuild?
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
==> 
:: PKGBUILD up to date, Skipping (1/9): edid-decode-git
:: PKGBUILD up to date, Skipping (2/9): firebird-nspire
:: PKGBUILD up to date, Skipping (3/9): python38
:: PKGBUILD up to date, Skipping (4/9): deltachat-desktop-git
:: Downloaded PKGBUILD (5/9): package-query
:: Downloaded PKGBUILD (6/9): teamviewer-beta
:: Downloaded PKGBUILD (7/9): google-chrome-dev
:: Downloaded PKGBUILD (8/9): camlpdf
:: Downloaded PKGBUILD (9/9): cpdf
  9 camlpdf                          (Installed) (Build Files Exist)
  8 cpdf                             (Installed) (Build Files Exist)
  7 google-chrome-dev                (Installed) (Build Files Exist)
  6 package-query                    (Installed) (Build Files Exist)
  5 firebird-nspire                  (Installed) (Build Files Exist)
  4 python38                         (Installed) (Build Files Exist)
  3 teamviewer-beta                  (Installed) (Build Files Exist)
  2 deltachat-desktop-git            (Installed) (Build Files Exist)
  1 edid-decode-git                  (Installed) (Build Files Exist)
==> Diffs to show?
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
==> A
(pager opens showing the diffs at this point, I hit `q` for all of them)
yay -Suy  3.90s user 0.36s system 37% cpu 11.346 total
```

config:

```
{
	"aururl": "https://aur.archlinux.org",
	"buildDir": "/home/florian/.cache/yay",
	"absdir": "/home/florian/.cache/yay/abs",
	"editor": "",
	"editorflags": "",
	"makepkgbin": "makepkg",
	"makepkgconf": "",
	"pacmanbin": "pacman",
	"pacmanconf": "/etc/pacman.conf",
	"tarbin": "bsdtar",
	"redownload": "no",
	"rebuild": "no",
	"batchinstall": false,
	"answerclean": "",
	"answerdiff": "A",
	"answeredit": "",
	"answerupgrade": "",
	"gitbin": "git",
	"gpgbin": "gpg",
	"gpgflags": "",
	"mflags": "",
	"sortby": "votes",
	"searchby": "name-desc",
	"gitflags": "",
	"removemake": "ask",
	"requestsplitn": 150,
	"sortmode": 0,
	"completionrefreshtime": 7,
	"sudoloop": false,
	"timeupdate": false,
	"devel": true,
	"cleanAfter": false,
	"gitclone": true,
	"provides": true,
	"pgpfetch": true,
	"upgrademenu": true,
	"cleanmenu": true,
	"diffmenu": true,
	"editmenu": true,
	"combinedupgrade": false,
	"useask": false
}
```

I tried setting `"answerdiff"` to `""` instead of `"A"`. Then when I use `A` manually, I get the same result. When I answer `N`, yay proceeds like expected.

### PR DESCRIPTION
**Pull request by Morganamilo**
std{out,err} all passed to the call so errors should print just as
before, the only difference is now yay will not abort after an error
occurs. We always provide a confirmation dialog after viewing diffs so
this should be safe.

Fixes #1091

### CODE REVIEW

File: install.go [hunk 1]
```diff
@@ -249,11 +249,7 @@ func install(parser *arguments) (err error) {
 		}
 
 		if len(toDiff) > 0 {
-			// TODO: PKGBUILD diffs should not return in case of err. Just print and continue
```
Comment (Morganamilo) [inline install.go]: Funny how this was there all alone. Maybe I'm physic and predicted this bug.

File: install.go [hunk 2]
```diff
@@ -732,7 +728,7 @@ func updatePkgbuildSeenRef(bases []Base, cloned stringset.StringSet) error {
 	return errMulti.Return()
 }
 
-func showPkgbuildDiffs(bases []Base, cloned stringset.StringSet) error {
+func showPkgbuildDiffs(bases []Base, cloned stringset.StringSet) {
 	var errMulti multierror.MultiError
```
Comment (Jguer) [inline install.go]: This MultiError is only accumulating errors which are never returned and never treated

Comment (Morganamilo) [reply install.go]: I kinda forgot those weren't the only two errors that can happen.
