### PR TITLE
Jguer/ /fix mflags

### LINKED ISSUE #1397: Yay seems to ignore / not pass --mflags to makepkg
#### Affected Version

`yay v10.1.0 - libalpm v12.0.2`

**Describe the bug**
Yay seems to not pass or ignore the flags which needed to be passed to makepkg. See "to reproduce step". But I pass the `--nocheck` flag, however the `check()` function in the PKGBUILD is still being executed. 

**To Reproduce**

`yay -S python-liblarch-git --noconfirm --noeditmenu --noupgrademenu --rebuild --mflags "--nocheck" `

**Expected behavior**

I expect makepkg to be executed with the `--nocheck` parameter. 

But once I downgrade to v10.0.4, then the issue is resolved.

**Output**

### v10.1.0 output
```
[0] % yay -S python-liblarch-git --noconfirm --noeditmenu --noupgrademenu --rebuild --mflags "--nocheck"   
:: Checking for conflicts...
:: Checking for inner conflicts...
[Aur:1]  python-liblarch-git-v3.0.r9.gebd05dd-2

  1 python-liblarch-git                      (Installed) (Build Files Exist)
==> Packages to cleanBuild?
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
==> 
:: PKGBUILD up to date, Skipping (1/1): python-liblarch-git
  1 python-liblarch-git                      (Installed) (Build Files Exist)
==> Diffs to show?
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
==> 
:: (1/1) Parsing SRCINFO: python-liblarch-git
==> Making package: python-liblarch-git v3.0.r9.gebd05dd-2 (Sat 24 Oct 2020 10:00:44 PM CEST)
==> Retrieving sources...
  -> Updating liblarch git repo...
Fetching origin
==> Validating source files with md5sums...
    liblarch ... Skipped
==> Making package: python-liblarch-git v3.0.r9.gebd05dd-2 (Sat 24 Oct 2020 10:00:59 PM CEST)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Updating liblarch git repo...
Fetching origin
==> Validating source files with md5sums...
    liblarch ... Skipped
==> Removing existing $srcdir/ directory...
==> Extracting sources...
  -> Creating working copy of liblarch git repo...
Cloning into 'liblarch'...
done.
==> Starting pkgver()...
==> Updated version: python-liblarch-git v3.0.r28.g17bf0bd-1
==> Sources are ready.
==> Making package: python-liblarch-git v3.0.r28.g17bf0bd-1 (Sat 24 Oct 2020 10:01:03 PM CEST)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> WARNING: Using existing $srcdir/ tree
==> Starting pkgver()...
==> Starting build()...
running build
running build_py
creating build
creating build/lib
creating build/lib/liblarch
copying liblarch/viewcount.py -> build/lib/liblarch
copying liblarch/__init__.py -> build/lib/liblarch
copying liblarch/viewtree.py -> build/lib/liblarch
copying liblarch/treenode.py -> build/lib/liblarch
copying liblarch/filteredtree.py -> build/lib/liblarch
copying liblarch/processqueue.py -> build/lib/liblarch
copying liblarch/tree.py -> build/lib/liblarch
copying liblarch/filters_bank.py -> build/lib/liblarch
creating build/lib/liblarch_gtk
copying liblarch_gtk/__init__.py -> build/lib/liblarch_gtk
copying liblarch_gtk/treemodel.py -> build/lib/liblarch_gtk
==> Starting check()...
....................................................................
----------------------------------------------------------------------
Ran 68 tests in 10.568s

OK
==> Entering fakeroot environment...
==> Starting package()...
running install
running build
running build_py
running install_lib
creating /home/sander/.cache/yay/python-liblarch-git/pkg/python-liblarch-git/usr
creating /home/sander/.cache/yay/python-liblarch-git/pkg/python-liblarch-git/usr/lib
creating /home/sander/.cache/yay/python-liblarch-git/pkg/python-liblarch-git/usr/lib/python3.8
creating /home/sander/.cache/yay/python-liblarch-git/pkg/python-liblarch-git/usr/lib/python3.8/site-packages
creating /home/sander/.cache/yay/python-liblarch-git/pkg/python-liblarch-git/usr/lib/python3.8/site-packages/liblarch_gtk
copying build/lib/liblarch_gtk/__init__.py -> /home/sander/.cache/yay/python-liblarch-git/pkg/python-liblarch-git/usr/lib/python3.8/site-packages/liblarch_gtk
copying build/lib/liblarch_gtk/treemodel.py -> /home/sander/.cache/yay/python-liblarch-git/pkg/python-liblarch-git/usr/lib/python3.8/site-packages/liblarch_gtk
creating /home/sander/.cache/yay/python-liblarch-git/pkg/python-liblarch-git/usr/lib/python3.8/site-packages/liblarch
copying build/lib/liblarch/viewcount.py -> /home/sander/.cache/yay/python-liblarch-git/pkg/python-liblarch-git/usr/lib/python3.8/site-packages/liblarch
copying build/lib/liblarch/__init__.py -> /home/sander/.cache/yay/python-liblarch-git/pkg/python-liblarch-git/usr/lib/python3.8/site-packages/liblarch
copying build/lib/liblarch/viewtree.py -> /home/sander/.cache/yay/python-liblarch-git/pkg/python-liblarch-git/usr/lib/python3.8/site-packages/liblarch
copying build/lib/liblarch/treenode.py -> /home/sander/.cache/yay/python-liblarch-git/pkg/python-liblarch-git/usr/lib/python3.8/site-packages/liblarch
copying build/lib/liblarch/filteredtree.py -> /home/sander/.cache/yay/python-liblarch-git/pkg/python-liblarch-git/usr/lib/python3.8/site-packages/liblarch
copying build/lib/liblarch/processqueue.py -> /home/sander/.cache/yay/python-liblarch-git/pkg/python-liblarch-git/usr/lib/python3.8/site-packages/liblarch
copying build/lib/liblarch/tree.py -> /home/sander/.cache/yay/python-liblarch-git/pkg/python-liblarch-git/usr/lib/python3.8/site-packages/liblarch
copying build/lib/liblarch/filters_bank.py -> /home/sander/.cache/yay/python-liblarch-git/pkg/python-liblarch-git/usr/lib/python3.8/site-packages/liblarch
byte-compiling /home/sander/.cache/yay/python-liblarch-git/pkg/python-liblarch-git/usr/lib/python3.8/site-packages/liblarch_gtk/__init__.py to __init__.cpython-38.pyc
byte-compiling /home/sander/.cache/yay/python-liblarch-git/pkg/python-liblarch-git/usr/lib/python3.8/site-packages/liblarch_gtk/treemodel.py to treemodel.cpython-38.pyc
byte-compiling /home/sander/.cache/yay/python-liblarch-git/pkg/python-liblarch-git/usr/lib/python3.8/site-packages/liblarch/viewcount.py to viewcount.cpython-38.pyc
byte-compiling /home/sander/.cache/yay/python-liblarch-git/pkg/python-liblarch-git/usr/lib/python3.8/site-packages/liblarch/__init__.py to __init__.cpython-38.pyc
byte-compiling /home/sander/.cache/yay/python-liblarch-git/pkg/python-liblarch-git/usr/lib/python3.8/site-packages/liblarch/viewtree.py to viewtree.cpython-38.pyc
byte-compiling /home/sander/.cache/yay/python-liblarch-git/pkg/python-liblarch-git/usr/lib/python3.8/site-packages/liblarch/treenode.py to treenode.cpython-38.pyc
byte-compiling /home/sander/.cache/yay/python-liblarch-git/pkg/python-liblarch-git/usr/lib/python3.8/site-packages/liblarch/filteredtree.py to filteredtree.cpython-38.pyc
byte-compiling /home/sander/.cache/yay/python-liblarch-git/pkg/python-liblarch-git/usr/lib/python3.8/site-packages/liblarch/processqueue.py to processqueue.cpython-38.pyc
byte-compiling /home/sander/.cache/yay/python-liblarch-git/pkg/python-liblarch-git/usr/lib/python3.8/site-packages/liblarch/tree.py to tree.cpython-38.pyc
byte-compiling /home/sander/.cache/yay/python-liblarch-git/pkg/python-liblarch-git/usr/lib/python3.8/site-packages/liblarch/filters_bank.py to filters_bank.cpython-38.pyc
writing byte-compilation script '/tmp/tmpc38m6o43.py'
/usr/bin/python /tmp/tmpc38m6o43.py
removing /tmp/tmpc38m6o43.py
running install_egg_info
Writing /home/sander/.cache/yay/python-liblarch-git/pkg/python-liblarch-git/usr/lib/python3.8/site-packages/liblarch-3.0.1-py3.8.egg-info
==> Tidying install...
  -> Removing libtool files...
  -> Purging unwanted files...
  -> Removing static library files...
  -> Stripping unneeded symbols from binaries and libraries...
  -> Compressing man and info pages...
==> Checking for packaging issues...
==> Creating package "python-liblarch-git"...
  -> Generating .PKGINFO file...
  -> Generating .BUILDINFO file...
  -> Generating .MTREE file...
  -> Compressing package...
==> Leaving fakeroot environment.
==> Finished making: python-liblarch-git v3.0.r28.g17bf0bd-1 (Sat 24 Oct 2020 10:01:19 PM CEST)
==> Cleaning up...
 -> Found git repo: github.com/liblarch/liblarch.git
[sudo] password for sander: 
loading packages...
warning: python-liblarch-git-v3.0.r28.g17bf0bd-1 is up to date -- reinstalling
resolving dependencies...
looking for conflicting packages...

Packages (1) python-liblarch-git-v3.0.r28.g17bf0bd-1

Total Installed Size:  0.26 MiB
Net Upgrade Size:      0.00 MiB

:: Proceed with installation? [Y/n] 
(1/1) checking keys in keyring                                                                                               [###########################################################################] 100%
(1/1) checking package integrity                                                                                             [###########################################################################] 100%
(1/1) loading package files                                                                                                  [###########################################################################] 100%
(1/1) checking for file conflicts                                                                                            [###########################################################################] 100%
(1/1) checking available disk space                                                                                          [###########################################################################] 100%
:: Processing package changes...
(1/1) reinstalling python-liblarch-git                                                                                       [###########################################################################] 100%
:: Running post-transaction hooks...
(1/1) Arming ConditionNeedsUpdate...
```

### v10.0.4 output
```
==> Making package: python-liblarch-git v3.0.r9.gebd05dd-2 (Sat 24 Oct 2020 08:41:48 PM UTC)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Updating liblarch git repo...
Fetching origin
==> Validating source files with md5sums...
    liblarch ... Skipped
==> Removing existing $srcdir/ directory...
==> Extracting sources...
  -> Creating working copy of liblarch git repo...
Cloning into 'liblarch'...
done.
==> Starting pkgver()...
==> Updated version: python-liblarch-git v3.0.r28.g17bf0bd-1
==> Sources are ready.
==> Making package: python-liblarch-git v3.0.r28.g17bf0bd-1 (Sat 24 Oct 2020 08:41:50 PM UTC)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> WARNING: Using existing $srcdir/ tree
==> Starting pkgver()...
==> Starting build()...
running build
running build_py
creating build
creating build/lib
creating build/lib/liblarch
copying liblarch/viewcount.py -> build/lib/liblarch
copying liblarch/__init__.py -> build/lib/liblarch
copying liblarch/processqueue.py -> build/lib/liblarch
copying liblarch/filters_bank.py -> build/lib/liblarch
copying liblarch/tree.py -> build/lib/liblarch
copying liblarch/treenode.py -> build/lib/liblarch
copying liblarch/viewtree.py -> build/lib/liblarch
copying liblarch/filteredtree.py -> build/lib/liblarch
creating build/lib/liblarch_gtk
copying liblarch_gtk/__init__.py -> build/lib/liblarch_gtk
copying liblarch_gtk/treemodel.py -> build/lib/liblarch_gtk
==> Entering fakeroot environment...
==> Starting package()...
running install
running build
running build_py
running install_lib
creating /tmp/gtg-git/python-liblarch-git/pkg/python-liblarch-git/usr
creating /tmp/gtg-git/python-liblarch-git/pkg/python-liblarch-git/usr/lib
creating /tmp/gtg-git/python-liblarch-git/pkg/python-liblarch-git/usr/lib/python3.8
creating /tmp/gtg-git/python-liblarch-git/pkg/python-liblarch-git/usr/lib/python3.8/site-packages
creating /tmp/gtg-git/python-liblarch-git/pkg/python-liblarch-git/usr/lib/python3.8/site-packages/liblarch_gtk
copying build/lib/liblarch_gtk/__init__.py -> /tmp/gtg-git/python-liblarch-git/pkg/python-liblarch-git/usr/lib/python3.8/site-packages/liblarch_gtk
copying build/lib/liblarch_gtk/treemodel.py -> /tmp/gtg-git/python-liblarch-git/pkg/python-liblarch-git/usr/lib/python3.8/site-packages/liblarch_gtk
creating /tmp/gtg-git/python-liblarch-git/pkg/python-liblarch-git/usr/lib/python3.8/site-packages/liblarch
copying build/lib/liblarch/viewcount.py -> /tmp/gtg-git/python-liblarch-git/pkg/python-liblarch-git/usr/lib/python3.8/site-packages/liblarch
copying build/lib/liblarch/__init__.py -> /tmp/gtg-git/python-liblarch-git/pkg/python-liblarch-git/usr/lib/python3.8/site-packages/liblarch
copying build/lib/liblarch/processqueue.py -> /tmp/gtg-git/python-liblarch-git/pkg/python-liblarch-git/usr/lib/python3.8/site-packages/liblarch
copying build/lib/liblarch/filters_bank.py -> /tmp/gtg-git/python-liblarch-git/pkg/python-liblarch-git/usr/lib/python3.8/site-packages/liblarch
copying build/lib/liblarch/tree.py -> /tmp/gtg-git/python-liblarch-git/pkg/python-liblarch-git/usr/lib/python3.8/site-packages/liblarch
copying build/lib/liblarch/treenode.py -> /tmp/gtg-git/python-liblarch-git/pkg/python-liblarch-git/usr/lib/python3.8/site-packages/liblarch
copying build/lib/liblarch/viewtree.py -> /tmp/gtg-git/python-liblarch-git/pkg/python-liblarch-git/usr/lib/python3.8/site-packages/liblarch
copying build/lib/liblarch/filteredtree.py -> /tmp/gtg-git/python-liblarch-git/pkg/python-liblarch-git/usr/lib/python3.8/site-packages/liblarch
byte-compiling /tmp/gtg-git/python-liblarch-git/pkg/python-liblarch-git/usr/lib/python3.8/site-packages/liblarch_gtk/__init__.py to __init__.cpython-38.pyc
byte-compiling /tmp/gtg-git/python-liblarch-git/pkg/python-liblarch-git/usr/lib/python3.8/site-packages/liblarch_gtk/treemodel.py to treemodel.cpython-38.pyc
byte-compiling /tmp/gtg-git/python-liblarch-git/pkg/python-liblarch-git/usr/lib/python3.8/site-packages/liblarch/viewcount.py to viewcount.cpython-38.pyc
byte-compiling /tmp/gtg-git/python-liblarch-git/pkg/python-liblarch-git/usr/lib/python3.8/site-packages/liblarch/__init__.py to __init__.cpython-38.pyc
byte-compiling /tmp/gtg-git/python-liblarch-git/pkg/python-liblarch-git/usr/lib/python3.8/site-packages/liblarch/processqueue.py to processqueue.cpython-38.pyc
byte-compiling /tmp/gtg-git/python-liblarch-git/pkg/python-liblarch-git/usr/lib/python3.8/site-packages/liblarch/filters_bank.py to filters_bank.cpython-38.pyc
byte-compiling /tmp/gtg-git/python-liblarch-git/pkg/python-liblarch-git/usr/lib/python3.8/site-packages/liblarch/tree.py to tree.cpython-38.pyc
byte-compiling /tmp/gtg-git/python-liblarch-git/pkg/python-liblarch-git/usr/lib/python3.8/site-packages/liblarch/treenode.py to treenode.cpython-38.pyc
byte-compiling /tmp/gtg-git/python-liblarch-git/pkg/python-liblarch-git/usr/lib/python3.8/site-packages/liblarch/viewtree.py to viewtree.cpython-38.pyc
byte-compiling /tmp/gtg-git/python-liblarch-git/pkg/python-liblarch-git/usr/lib/python3.8/site-packages/liblarch/filteredtree.py to filteredtree.cpython-38.pyc
writing byte-compilation script '/tmp/tmpsvzvv4iu.py'
/usr/bin/python /tmp/tmpsvzvv4iu.py
removing /tmp/tmpsvzvv4iu.py
running install_egg_info
Writing /tmp/gtg-git/python-liblarch-git/pkg/python-liblarch-git/usr/lib/python3.8/site-packages/liblarch-3.0.1-py3.8.egg-info
==> Tidying install...
  -> Removing libtool files...
  -> Purging unwanted files...
  -> Removing static library files...
  -> Stripping unneeded symbols from binaries and libraries...
  -> Compressing man and info pages...
==> Checking for packaging issues...
==> Creating package "python-liblarch-git"...
  -> Generating .PKGINFO file...
  -> Generating .BUILDINFO file...
  -> Generating .MTREE file...
  -> Compressing package...
==> Leaving fakeroot environment.
==> Finished making: python-liblarch-git v3.0.r28.g17bf0bd-1 (Sat 24 Oct 2020 08:41:52 PM UTC)
==> Cleaning up...
 -> Found git repo: github.com/liblarch/liblarch.git
loading packages...
resolving dependencies...
looking for conflicting packages...
Packages (1) python-liblarch-git-v3.0.r28.g17bf0bd-1
Total Installed Size:  0.26 MiB
:: Proceed with installation? [Y/n] 
checking keyring...
checking package integrity...
loading package files...
checking for file conflicts...
:: Processing package changes...
installing python-liblarch-git...
:: Running post-transaction hooks...
```

### PR DESCRIPTION
**Pull request by Jguer**
fixes #1397

### CODE REVIEW

File: pkg/settings/parser.go [hunk 1]
```diff
@@ -817,6 +817,8 @@ func (a *Arguments) ParseCommandLine(config *Configuration) error {
 	}
 
 	a.extractYayOptions(config)
+	config.Runtime.CmdBuilder.MakepkgFlags = strings.Split(config.MFlags, " ")
```
Comment (Morganamilo) [inline pkg/settings/parser.go:820]: Previously SplitWhitespace was used for this.
